### ISSUE TITLE
건화

### ISSUE THREAD

**Issue by taeho0888** [GoodBoyDevelopers/Server#1]
## Description
유튜브 링크를 받아서 영상 요약하는 부분

## Todo
- [ ] 유튜브 스크립트 추출
- [ ] 추출한 스크립트 openai를 통해 요약
- [ ] 추출한 스크립트를 통해 영상의 키워드(핵심 이슈) 최대 3개 뽑아내기

## ETC
유튜브 스크립트 추출은 다른 사람들도 쓰는 부분이니 언능 구현해서 푸시 부탁드려요~!
